// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: proto/message.proto

package message

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Position for players and bullets
type Position struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             float64                `protobuf:"fixed64,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             float64                `protobuf:"fixed64,2,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Position) Reset() {
	*x = Position{}
	mi := &file_proto_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Position) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Position) ProtoMessage() {}

func (x *Position) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Position.ProtoReflect.Descriptor instead.
func (*Position) Descriptor() ([]byte, []int) {
	return file_proto_message_proto_rawDescGZIP(), []int{0}
}

func (x *Position) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Position) GetY() float64 {
	if x != nil {
		return x.Y
	}
	return 0
}

// Bullet - sent over WebSocket
type Bullet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            float64                `protobuf:"fixed64,1,opt,name=id,proto3" json:"id,omitempty"`
	Position      *Position              `protobuf:"bytes,2,opt,name=position,proto3" json:"position,omitempty"`
	Rotation      float64                `protobuf:"fixed64,3,opt,name=rotation,proto3" json:"rotation,omitempty"`
	Expired       bool                   `protobuf:"varint,4,opt,name=expired,proto3" json:"expired,omitempty"`
	OwnerId       int32                  `protobuf:"varint,5,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bullet) Reset() {
	*x = Bullet{}
	mi := &file_proto_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bullet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bullet) ProtoMessage() {}

func (x *Bullet) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bullet.ProtoReflect.Descriptor instead.
func (*Bullet) Descriptor() ([]byte, []int) {
	return file_proto_message_proto_rawDescGZIP(), []int{1}
}

func (x *Bullet) GetId() float64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Bullet) GetPosition() *Position {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *Bullet) GetRotation() float64 {
	if x != nil {
		return x.Rotation
	}
	return 0
}

func (x *Bullet) GetExpired() bool {
	if x != nil {
		return x.Expired
	}
	return false
}

func (x *Bullet) GetOwnerId() int32 {
	if x != nil {
		return x.OwnerId
	}
	return 0
}

// Player - sent over WebSocket
type Player struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Color         string                 `protobuf:"bytes,3,opt,name=color,proto3" json:"color,omitempty"`
	Position      *Position              `protobuf:"bytes,4,opt,name=position,proto3" json:"position,omitempty"`
	IsReady       bool                   `protobuf:"varint,5,opt,name=is_ready,json=isReady,proto3" json:"is_ready,omitempty"`
	InBush        bool                   `protobuf:"varint,6,opt,name=in_bush,json=inBush,proto3" json:"in_bush,omitempty"`
	Rotation      float64                `protobuf:"fixed64,7,opt,name=rotation,proto3" json:"rotation,omitempty"`
	Kills         int32                  `protobuf:"varint,8,opt,name=kills,proto3" json:"kills,omitempty"`
	Health        int32                  `protobuf:"varint,9,opt,name=health,proto3" json:"health,omitempty"`
	MaxHealth     int32                  `protobuf:"varint,10,opt,name=max_health,json=maxHealth,proto3" json:"max_health,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Player) Reset() {
	*x = Player{}
	mi := &file_proto_message_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Player) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Player) ProtoMessage() {}

func (x *Player) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Player.ProtoReflect.Descriptor instead.
func (*Player) Descriptor() ([]byte, []int) {
	return file_proto_message_proto_rawDescGZIP(), []int{2}
}

func (x *Player) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Player) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Player) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *Player) GetPosition() *Position {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *Player) GetIsReady() bool {
	if x != nil {
		return x.IsReady
	}
	return false
}

func (x *Player) GetInBush() bool {
	if x != nil {
		return x.InBush
	}
	return false
}

func (x *Player) GetRotation() float64 {
	if x != nil {
		return x.Rotation
	}
	return 0
}

func (x *Player) GetKills() int32 {
	if x != nil {
		return x.Kills
	}
	return 0
}

func (x *Player) GetHealth() int32 {
	if x != nil {
		return x.Health
	}
	return 0
}

func (x *Player) GetMaxHealth() int32 {
	if x != nil {
		return x.MaxHealth
	}
	return 0
}

// Payload - WebSocket message payload
type Payload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Players       []*Player              `protobuf:"bytes,1,rep,name=players,proto3" json:"players,omitempty"`
	Position      *Position              `protobuf:"bytes,2,opt,name=position,proto3,oneof" json:"position,omitempty"`
	Bullet        *Bullet                `protobuf:"bytes,3,opt,name=bullet,proto3,oneof" json:"bullet,omitempty"`
	IsReady       *bool                  `protobuf:"varint,5,opt,name=is_ready,json=isReady,proto3,oneof" json:"is_ready,omitempty"`
	InBush        *bool                  `protobuf:"varint,6,opt,name=in_bush,json=inBush,proto3,oneof" json:"in_bush,omitempty"`
	Health        *int32                 `protobuf:"varint,7,opt,name=health,proto3,oneof" json:"health,omitempty"`
	Rotation      *float64               `protobuf:"fixed64,8,opt,name=rotation,proto3,oneof" json:"rotation,omitempty"`
	Kills         *int32                 `protobuf:"varint,9,opt,name=kills,proto3,oneof" json:"kills,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Payload) Reset() {
	*x = Payload{}
	mi := &file_proto_message_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Payload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Payload) ProtoMessage() {}

func (x *Payload) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Payload.ProtoReflect.Descriptor instead.
func (*Payload) Descriptor() ([]byte, []int) {
	return file_proto_message_proto_rawDescGZIP(), []int{3}
}

func (x *Payload) GetPlayers() []*Player {
	if x != nil {
		return x.Players
	}
	return nil
}

func (x *Payload) GetPosition() *Position {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *Payload) GetBullet() *Bullet {
	if x != nil {
		return x.Bullet
	}
	return nil
}

func (x *Payload) GetIsReady() bool {
	if x != nil && x.IsReady != nil {
		return *x.IsReady
	}
	return false
}

func (x *Payload) GetInBush() bool {
	if x != nil && x.InBush != nil {
		return *x.InBush
	}
	return false
}

func (x *Payload) GetHealth() int32 {
	if x != nil && x.Health != nil {
		return *x.Health
	}
	return 0
}

func (x *Payload) GetRotation() float64 {
	if x != nil && x.Rotation != nil {
		return *x.Rotation
	}
	return 0
}

func (x *Payload) GetKills() int32 {
	if x != nil && x.Kills != nil {
		return *x.Kills
	}
	return 0
}

// Message - WebSocket message wrapper
type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *int32                 `protobuf:"varint,1,opt,name=id,proto3,oneof" json:"id,omitempty"`
	Event         string                 `protobuf:"bytes,2,opt,name=event,proto3" json:"event,omitempty"`
	Time          uint64                 `protobuf:"varint,3,opt,name=time,proto3" json:"time,omitempty"`
	Payload       *Payload               `protobuf:"bytes,4,opt,name=payload,proto3,oneof" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_proto_message_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_proto_message_proto_rawDescGZIP(), []int{4}
}

func (x *Message) GetId() int32 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *Message) GetEvent() string {
	if x != nil {
		return x.Event
	}
	return ""
}

func (x *Message) GetTime() uint64 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *Message) GetPayload() *Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

var File_proto_message_proto protoreflect.FileDescriptor

const file_proto_message_proto_rawDesc = "" +
	"\n" +
	"\x13proto/message.proto\"&\n" +
	"\bPosition\x12\f\n" +
	"\x01x\x18\x01 \x01(\x01R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x01R\x01y\"\x90\x01\n" +
	"\x06Bullet\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x01R\x02id\x12%\n" +
	"\bposition\x18\x02 \x01(\v2\t.PositionR\bposition\x12\x1a\n" +
	"\brotation\x18\x03 \x01(\x01R\brotation\x12\x18\n" +
	"\aexpired\x18\x04 \x01(\bR\aexpired\x12\x19\n" +
	"\bowner_id\x18\x05 \x01(\x05R\aownerId\"\x86\x02\n" +
	"\x06Player\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05color\x18\x03 \x01(\tR\x05color\x12%\n" +
	"\bposition\x18\x04 \x01(\v2\t.PositionR\bposition\x12\x19\n" +
	"\bis_ready\x18\x05 \x01(\bR\aisReady\x12\x17\n" +
	"\ain_bush\x18\x06 \x01(\bR\x06inBush\x12\x1a\n" +
	"\brotation\x18\a \x01(\x01R\brotation\x12\x14\n" +
	"\x05kills\x18\b \x01(\x05R\x05kills\x12\x16\n" +
	"\x06health\x18\t \x01(\x05R\x06health\x12\x1d\n" +
	"\n" +
	"max_health\x18\n" +
	" \x01(\x05R\tmaxHealth\"\xe8\x02\n" +
	"\aPayload\x12!\n" +
	"\aplayers\x18\x01 \x03(\v2\a.PlayerR\aplayers\x12*\n" +
	"\bposition\x18\x02 \x01(\v2\t.PositionH\x00R\bposition\x88\x01\x01\x12$\n" +
	"\x06bullet\x18\x03 \x01(\v2\a.BulletH\x01R\x06bullet\x88\x01\x01\x12\x1e\n" +
	"\bis_ready\x18\x05 \x01(\bH\x02R\aisReady\x88\x01\x01\x12\x1c\n" +
	"\ain_bush\x18\x06 \x01(\bH\x03R\x06inBush\x88\x01\x01\x12\x1b\n" +
	"\x06health\x18\a \x01(\x05H\x04R\x06health\x88\x01\x01\x12\x1f\n" +
	"\brotation\x18\b \x01(\x01H\x05R\brotation\x88\x01\x01\x12\x19\n" +
	"\x05kills\x18\t \x01(\x05H\x06R\x05kills\x88\x01\x01B\v\n" +
	"\t_positionB\t\n" +
	"\a_bulletB\v\n" +
	"\t_is_readyB\n" +
	"\n" +
	"\b_in_bushB\t\n" +
	"\a_healthB\v\n" +
	"\t_rotationB\b\n" +
	"\x06_kills\"\x84\x01\n" +
	"\aMessage\x12\x13\n" +
	"\x02id\x18\x01 \x01(\x05H\x00R\x02id\x88\x01\x01\x12\x14\n" +
	"\x05event\x18\x02 \x01(\tR\x05event\x12\x12\n" +
	"\x04time\x18\x03 \x01(\x04R\x04time\x12'\n" +
	"\apayload\x18\x04 \x01(\v2\b.PayloadH\x01R\apayload\x88\x01\x01B\x05\n" +
	"\x03_idB\n" +
	"\n" +
	"\b_payloadB\n" +
	"Z\b/messageb\x06proto3"

var (
	file_proto_message_proto_rawDescOnce sync.Once
	file_proto_message_proto_rawDescData []byte
)

func file_proto_message_proto_rawDescGZIP() []byte {
	file_proto_message_proto_rawDescOnce.Do(func() {
		file_proto_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_message_proto_rawDesc), len(file_proto_message_proto_rawDesc)))
	})
	return file_proto_message_proto_rawDescData
}

var file_proto_message_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_message_proto_goTypes = []any{
	(*Position)(nil), // 0: Position
	(*Bullet)(nil),   // 1: Bullet
	(*Player)(nil),   // 2: Player
	(*Payload)(nil),  // 3: Payload
	(*Message)(nil),  // 4: Message
}
var file_proto_message_proto_depIdxs = []int32{
	0, // 0: Bullet.position:type_name -> Position
	0, // 1: Player.position:type_name -> Position
	2, // 2: Payload.players:type_name -> Player
	0, // 3: Payload.position:type_name -> Position
	1, // 4: Payload.bullet:type_name -> Bullet
	3, // 5: Message.payload:type_name -> Payload
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_proto_message_proto_init() }
func file_proto_message_proto_init() {
	if File_proto_message_proto != nil {
		return
	}
	file_proto_message_proto_msgTypes[3].OneofWrappers = []any{}
	file_proto_message_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_message_proto_rawDesc), len(file_proto_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_message_proto_goTypes,
		DependencyIndexes: file_proto_message_proto_depIdxs,
		MessageInfos:      file_proto_message_proto_msgTypes,
	}.Build()
	File_proto_message_proto = out.File
	file_proto_message_proto_goTypes = nil
	file_proto_message_proto_depIdxs = nil
}
